### ISSUE TITLE
signed/unsigned mismatch Error

### ISSUE THREAD

**Issue by Enigman2011** [mloskot/jxr-refsoft#1]
It gives this error when i want to Build in Visual studio

2>c:\users\enigma\desktop\....\new folder (2)\jxr-refsoft\src\file.c(345): warning C4018: '>=': signed/unsigned mismatch
2>c:\users\enigma\desktop\....\new folder (2)\jxr-refsoft\src\file.c(2814): warning C4018: '<': signed/unsigned mismatch

**Comment by mloskot** [comment]
It's a warning not an error.
It should be easy to fix if you want.

Mind you, I'm not the author or maintainer of this project

**Comment by Enigman2011** [comment]
But how can I fix the issue?

**Comment by Enigman2011** [comment]
oh By the way there are manyyy other errorssss....
Do you have any other stable version?

**Comment by mloskot** [comment]
> But how can I fix the issue?

As any C/C++ compilation warnings or errors.

> By the way there are manyyy other errorssss....

I don't care. If you care, solve them yourself.

> Do you have any other stable version?

Read description of this repo or the main README again and you will find out an alternative.

Let me repeat myself: I don't develop this library, I don't maintain it, I don't support it.

It is just a mirror copy for my own purposes and for those who want to find the JPEG XR ref implementation sources easier via GitHub.

**Comment by mloskot** [comment]
Don't be lazy, learn and do your homework!

p.s. You may want to check S and Y keys on your keyboard, they seem to be jamming
